### ISSUE TITLE
Add multiple recipients to email?

### ISSUE THREAD

**Issue by holtzermann17** [emacs-helm/helm-mu#15]
The doc string for `helm-mu-compose-mail` says "Compose a new email directed to the selected contacts."  However the code only adds one recipient.  Indeed, the current model seems to be one recipient per email.  It would be nice to supplement "<kbd>C-j</kbd>: Compose email addressed to this contact (keeping session)" with something like  "<kbd>C-k</kbd>: Add this contact to current email draft (keeping session)".

**Comment by holtzermann17** [comment]
Here's a way to add "copy address to kill ring" as the action attached to <kbd>F2</kbd>:

``` emacs-lisp
(helm-add-action-to-source
 "Copy address"
 #'(lambda (candidate)
     (with-temp-buffer
       (insert candidate)
       (goto-char (point-min))
       (delete-horizontal-space)
       (delete-trailing-whitespace)
       (when (search-forward-regexp "\\s " nil t)
	 (let ((name (buffer-substring-no-properties (point) (point-max))))
	   (delete-region (point) (point-max))
	   (goto-char (point-min))
	   (insert (concat name " <"))
	   (delete-trailing-whitespace)
	   (goto-char (point-max))
	   (insert ">")
	   (goto-char (point-min))
	   (delete-horizontal-space)))
       (copy-region-as-kill (point-min) (point-max))))
 helm-source-mu-contacts
 1)
```

... but I also noticed that pressing <kbd>TAB</kbd> prompts for more addresses when filling out the `To:` field.  The Helm interface is slightly different, not sure why.  For some reason it might not have been working but I don't have a formal bug report on that.

**Comment by tmalsburg** [comment]
I agree that helm-mu should have better support for emails with multiple recipients.  My approach is typically to mark entries and then select an action instead of using keep-session.  But to each his own.  Not sure if I will have time to work on this in the near future.
