### ISSUE TITLE
Unsupported header field (:thread-subject)

### ISSUE THREAD

**Issue by jagrg** [emacs-helm/helm-mu#17]
```
Debugger entered--Lisp error: (error #("[mu4e] Unsupported header field (:thread-subject)" 1 5 (face mu4e-title-face)))
  signal(error (#("[mu4e] Unsupported header field (:thread-subject)" 1 5 (face mu4e-title-face))))
  error("%s" #("[mu4e] Unsupported header field (:thread-subject)" 1 5 (face mu4e-title-face)))
  mu4e-error("Unsupported header field (%S)" :thread-subject)
```

**Comment by tmalsburg** [comment]
This looks more like an error in [mu4e](https://github.com/djcb/mu).

**Comment by jagrg** [comment]
This is what djcb had to day about the problem:

> It's a problem in helm-mu-candidate-formatter, it's missing thread-subject. In general, the code seems to depend on a bunch of mu4e-internals, which is not recommended.

> Please take it up with the helm-mu folks -- thanks!

https://github.com/djcb/mu/issues/643

**Comment by edumerco** [comment]
Hi Titus. 

Yesterday I installed the last version of helm-mu-20151019.944 and I still got the same error... 
Can I help to debug/test somehow? I don't know how to program, but I can follow instructions and report. :)
Thanks...

**Comment by tmalsburg** [comment]
Hi @edumerco, thanks for reporting this.  I have never encountered this error.  So the first thing I would need is a recipe for reproducing this problem.

**Comment by tmalsburg** [comment]
Please also post the precise error message that you get.

**Comment by edumerco** [comment]
Hi Titus. 
Now it works! I tried it yesterday and it didn't... could it be that I restarted Emacs this morning? 
I thought that after running eval-buffer in .emacs that wasn't necessary. 

Thanks for your patience with this and I'm sorry to bother. 
Should we close this now? 

Best... :)

**Comment by tmalsburg** [comment]
No problem. Thanks for the update.
