### ISSUE TITLE
helm-mu-contacts: Visibility with dark theme

### ISSUE THREAD

**Issue by floli** [emacs-helm/helm-mu#18]
I use the manoj-dark theme.

The contact names that ```helm-mu-contacts``` returns are barely visible. The mail addresses are visible, the matched part too, but the non matched is completely invisible, i.e. same color as background.

**Comment by floli** [comment]
I have added a pull request #19 that adds faces for dark backgrounds.

**Comment by tmalsburg** [comment]
Merged, thanks!
