### ISSUE TITLE
Select e-mail address without composing a new email

### ISSUE THREAD

**Issue by peterwvj** [emacs-helm/helm-mu#35]
I just started managing my emails using emacs/mu4e/helm-mu so please bear with me :)

When I'm using `helms-mu-contacts` to search my contacts helm also composes a new email and puts the chosen contact as the receiver of the email. What's the best way to auto-complete the email address proposal _without_ also composing a new email? I want to do this, when I'm forwarding emails.

**Comment by tmalsburg** [comment]
You are right, there is currently no way to copy or insert an email-address with `helm-mu-contacts`.  It's actually a feature that I wanted for a long time but I never got around adding although it's pretty simple to do.  Do you wanna give it a shot?  You could use `helm-mu-action-get-contact-emails` as the template for two new actions.  One for inserting selected email addresses at point (use ìnsert`), and one for copying the selected email addresses to the clipboard (use `kill-new`).

**Comment by peterwvj** [comment]
Thanks for your input - it was very useful!

So I thought it might be useful to have it as two separate features - one that copies the email and another feature that inserts the email at point.

The `helm-mu-contacts-insert` and `helm-mu-contacts-copy` functions, shown below, achieve this. I've never really written Elisp code before so the code quality is very poor - sorry about this.


~~~
(defun insert-contact (candidate)
  "Insert contact at point"
  (insert (helm-mu-format-contact candidate)))

(defvar helm-source-mu-contacts-insert
  (helm-build-in-buffer-source "Search contacts with mu"
    :data #'helm-mu-contacts-init
    :filtered-candidate-transformer #'helm-mu-contacts-transformer
    :fuzzy-match nil
    :action '(("Insert contact at point" . insert-contact)
              ("Get the emails from/to given contacts" . helm-mu-action-get-contact-emails))))

(defun helm-mu-contacts-insert ()
  "Search for contacts."
  (interactive)
  (helm :sources 'helm-source-mu-contacts-insert
        :buffer "*helm mu contacts*"))



(defun copy-contact (candidate)
  "Copy contact to clipboard"
  (kill-new (helm-mu-format-contact candidate)))

(defvar helm-source-mu-contacts-copy
  (helm-build-in-buffer-source "Search contacts with mu"
    :data #'helm-mu-contacts-init
    :filtered-candidate-transformer #'helm-mu-contacts-transformer
    :fuzzy-match nil
    :action '(("Copy contact to clipboard" . copy-contact)
              ("Get the emails from/to given contacts" . helm-mu-action-get-contact-emails))))

(defun helm-mu-contacts-copy ()
  "Search for contacts."
  (interactive)
  (helm :sources 'helm-source-mu-contacts-copy
        :buffer "*helm mu contacts*"))
~~~

**Comment by tmalsburg** [comment]
You don't need to build separate helm-sources.  Just add new actions like `helm-mu-action-get-contact-emails` and add them to the existing source (`helm-source-mu-contacts`). This way, when you select a contact and press TAB you have a list of four actions (the two existing actions, plus the new actions) from which can select one.

**Comment by peterwvj** [comment]
Right! I see what you mean. What about something like:

~~~

(defvar helm-source-mu-contacts
  (helm-build-in-buffer-source "Search contacts with mu"
    :data #'helm-mu-contacts-init
    :filtered-candidate-transformer #'helm-mu-contacts-transformer
    :fuzzy-match nil
    :action '(("Compose email addressed to this contact" . helm-mu-compose-mail)
              ("Get the emails from/to given contacts" . helm-mu-action-get-contact-emails)
              ("Copy contact" . copy-contact)
              ("Insert contact" . insert-contact))))
....
(defun insert-contact (candidate)
  "Insert contact at point"
  (insert (helm-mu-format-contact candidate)))

(defun copy-contact (candidate)
  "Copy contact to clipboard"
  (kill-new (helm-mu-format-contact candidate)))

~~~

**Comment by tmalsburg** [comment]
See a8ea0a2a69c8c5fa1302f2dcdd1a7cfb7b9f4fd0.  Hope it works as expected.

**Comment by peterwvj** [comment]
It works perfect. Thanks for all your help - I really appreciate it!

**Comment by tmalsburg** [comment]
Great.  Thanks for raising the issue.  I'm already using this feature a lot. :-)
