### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by MaksVal** [emacs-helm/helm-mu#36]
Hi! 
Thanks for your plugin!

How I can use autocomplete in message mode? Example, like is that https://github.com/auto-complete/popup-el/issues/102

Thanks!

**Comment by tmalsburg** [comment]
helm-mu builds on Mu4e and Mu4e already has address autocompletion. Also, autocompletion is not really in the scope of helm-mu.  Perhaps post an issue for Mu4e?
