### ISSUE TITLE
helm-make-source fails

### ISSUE THREAD

**Issue by 2mc** [emacs-helm/helm-mu#37]
Hello, 

while using 'helm-mu-20160531.1031' with  'helm-core-20160817.1042' from MELPA on 'GNU Emacs 25.1.1 (x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F1713))'

just after 

     (require 'helm-mu)

this final error is thrown:

    Debugger entered--Lisp error: (invalid-slot-name "#<helm-source-async helm-source-async>"  :matchplugin) signal(invalid-slot-name ("#<helm-source-async helm-source-async>" :matchplugin))

**Comment by thierryvolpiatto** [comment]
2mc <notifications@github.com> writes:

> Hello,
>
> while using 'helm-mu-20160531.1031' with 'helm-core-20160817.1042' from MELPA on 'GNU Emacs 25.1.1 (x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5
> (Build 14F1713))'
>
> just after
>
>  (require 'helm-mu)
>
> this final error is thrown:
>
> Debugger entered--Lisp error: (invalid-slot-name "#<helm-source-async
> helm-source-async>" :matchplugin) signal(invalid-slot-name
> ("#<helm-source-async helm-source-async>" :matchplugin))

Please update helm-mu, this have been fixed.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

> Please update helm-mu, this have been fixed.

You will have to wait melpa update, I thought I pushed changes upstream
but it was on my own fork, now merged upstream, sorry for inconvenience.

@titus FYI :matchplugin is now named :multimatch.
Also, unrelated to this fuzzy matching is disabled by default, so
`:fuzzy-match nil` is not needed (This is not new, it is like this since
first implementation of fuzzy).

Thanks.

-- 
Thierry

**Comment by tmalsburg** [comment]
Sorry everyone, I'm currently traveling, reception is very spotty and my laptop's display is dying.  @thierryvolpiatto, I renamed the slot in c1ad53be0e6110c2490d7c908d321a5a8fc07073.  Can we close this issue?

**Comment by thierryvolpiatto** [comment]
Titus von der Malsburg <notifications@github.com> writes:


> @thierryvolpiatto, I renamed the slot in c1ad53b. Can we close this
> issue?

It was already done ;-) but yes we can close this bug.

-- 
Thierry

**Comment by tmalsburg** [comment]
Ha, I saw it after I wrote the message. Thanks, Thierry!
