### ISSUE TITLE
helm-mu doesn't handle contexts

### ISSUE THREAD

**Issue by conornash** [emacs-helm/helm-mu#41]
When I configure mu4e to use contexts helm-mu no longer shows any results. Instead of a list of candidates I see (I think) a time value https://www.dropbox.com/s/4msllg4ndis975j/Screenshot%202017-06-24%2015.50.20.png?dl=0

How can I get helm-mu to work correctly with contexts?

**Comment by tmalsburg** [comment]
I'm not really familiar with contexts but I'm surprised to read that they interact with helm-mu.  Aren't contexts used to change harmless things like your name, email address, and signature?  Helm-mu doesn't touch these things so I don't see how contexts could affect helm-mu.  Do you get an error message in the `*Messages*` buffer?

**Comment by conornash** [comment]
After enabling Helm Debug Log (https://github.com/emacs-helm/helm/blob/master/helm.el#L245) and inspecting errors, it turns out this was actually related to not finding the `sed` executable. Thank you for your help 👍

**Comment by tmalsburg** [comment]
Ah, glad you figured it out.  I guess we should have an appropriate error message for these cases.
