### ISSUE TITLE
Add a setting to configure initial search string in mu4e-headers-mode 

### ISSUE THREAD

**Issue by livnev** [emacs-helm/helm-mu#47]
From the code:

```elisp
(defun helm-mu ()
  "Search for emails.  If started in mu4e-headers-view, the
current query will be used to initialize the search.  Otherwise
`helm-mu-default-search-string' will be used."
  (interactive)
  (let* ((query (if (eq major-mode 'mu4e-headers-mode)
                    (mu4e-last-query)
                  helm-mu-default-search-string))
                  ...
```

It would be nice if there was a way to configure it use `helm-mu-default-search-string` even when starting the search from `mu4e-headers-mode`. Perhaps `helm-mu-default-to-last-query` ?

**Comment by tmalsburg** [comment]
Perhaps a defcustom `helm-mu-always-use-default-search-string`?

**Comment by livnev** [comment]
@tmalsburg Yup, exactly! Shall I make a PR?

**Comment by tmalsburg** [comment]
Yes, please.

On April 10, 2019 1:29:24 PM GMT+02:00, livnev <notifications@github.com> wrote:
>@tmalsburg Yup, exactly! Shall I make a PR?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/emacs-helm/helm-mu/issues/47#issuecomment-481652111

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
