### ISSUE TITLE
[RFE] Add ~/.mailrc aliases to the list returned by helm-mu

### ISSUE THREAD

**Issue by jpggithub** [emacs-helm/helm-mu#50]
Hi
Is there a way to easily add the aliases of `~/.mailrc` to the liste returned by helm-mu?

I have searched on the web. Surprisingly I have found nothing to "link" helm and the contents of ~/.mailrc, or mail-abbrevs

Thanks for your attention

**Comment by tmalsburg** [comment]
Are you talking about the list of contacts returned by `helm-mu-contacts`?  This specific helm extension is a front-end for the mail indexer mu, so the feature you're asking about is not in the scope of helm-mu.  However, you can probably write your own helm extension for mailrc aliases in just a small handful of lines of code.

**Comment by jpggithub** [comment]
Thanks for you kind answer.
Sorry but I'm can't write this kind extension and I think that it could be at least an option of `helm-mu-contacts` to include the aliases defined in mailrc.

**Comment by tmalsburg** [comment]
Here's a tutorial showing how to make helm extensions:

https://wikemacs.org/wiki/How_to_write_helm_extensions

**Comment by jpggithub** [comment]
Thanks ;-)

**Comment by student-sx** [comment]
@jpggithub did you manage to solve the problem? I just wanted do ask the same question.

**Comment by jpggithub** [comment]
@student-sx sorry but I didn't find a complete satisfying solution :/ 
See also https://github.com/djcb/mu/issues/1897
