### ISSUE TITLE
Breaking change

### ISSUE THREAD

**Issue by danielfleischer** [emacs-helm/helm-mu#54]
Hi, due to some change in helm recently (recent months) the package breaks in the following way: after typing some text and getting a buffer with the relevant search results, when you press "enter" on one of the emails, you end up with a list of all emails, unrelated to the search query.

**Comment by tmalsburg** [comment]
Thanks for reporting. I can't reproduce this problem. Works as expected on my system.  Could you please make an minimal reproducible example that works with `emacs -Q`.  Thank you.

**Comment by danielfleischer** [comment]
Using git bisect I identified this [commit](https://github.com/emacs-helm/helm/commit/ae8721ca331a10a3ce3a8d86570108f11709381b). 

I don't know how to give a "clean" example; you need to load mu4e, helm, helm-mu and do a search and see the results ignore the candidates.

**Comment by tmalsburg** [comment]
Thanks. This commit is from just 3 days ago and I don't have it yet on my system.  Will test later ...

**Comment by thierryvolpiatto** [comment]
Hello Titus, I commited a change which should fix your issue, see https://github.com/emacs-helm/helm/commit/26313b28d1c57ac0b46fec4fbf9741358050da03

**Comment by tmalsburg** [comment]
As far as I can tell everything works as expected now, thanks to your changes in helm-mu.  Thank you very much, Thierry!

**Comment by danielfleischer** [comment]
Looks like a regression to me. 

**Old behavior**: when typing, the mu4e-headers buffer changes dynamically. When pressing enter we "freeze" the query and can browse the search results, opening individual emails. 

**New behavior:** typing is the same. Now when you press enter, the only email left in the buffer is the one you had your cursor on and the query is `msgid:...`, i.e. the query singled out  a single email and ignores what you typed.

**Comment by tmalsburg** [comment]
Ah you're right, and I remember now why I had used `mu4e-headers-search` in `helm-mu-display-email` instead of `mu4e-view-message-with-message-id`. I, too, would like to get the old behavior back, but I'm not sure it's possible after the change in helm?  As a workaround, you can use `S-<return>` to open the current helm-mu search in a Mu4e headers view.  Not the same but perhaps useful nonetheless.

**Comment by tmalsburg** [comment]
I reverted to the old method now.  Seems to work on in my setup.  Please check and confirm.  Thank you!

**Comment by danielfleischer** [comment]
Perfect, works as expected before the helm change! The is `S-<ret>` is a nice addition. Thanks!
