### ISSUE TITLE
No emails found:  "[Mu Process Finish- (0 results)]"

### ISSUE THREAD

**Issue by timmli** [emacs-helm/helm-mu#56]
Since around updating to mu4e v1.10 and moving my xapian directory away from ~/.cache/mu, helm-mu can no longer find my emails. It does start and the prompt is shown, but it does not show any search results (Modeline says: "[Mu Process Finish- (0 results)]"). No problems with mu4e though. 

Any idea what I can try to fix it?

I'm running mu4e v1.10.2 and helm-mu v20230408.2126.

**Comment by tmalsburg** [comment]
There was a recent glitch due to a change in mu4e.  Please install the latest version of mu4e (from git).

For reference: https://github.com/djcb/mu/issues/2470

I'm closing this issue but feel free to reopen if necessary.

**Comment by timmli** [comment]
In fact, the --after option was reintroduced in v1.10.2 which I use: https://github.com/djcb/mu/blob/v1.10.2/man/mu-cfind.1.org

But I somehow forgot to rebuild the database after upgrading mu. :1st_place_medal: 

Thanks for your quick response!

**Comment by timmli** [comment]
I later found out that the reason was not that I had forgotten to rebuild the database, but that I was using the option `--muhome` when calling `mu init` and `mu index`. 

In the comment above (https://github.com/emacs-helm/helm-mu/issues/56#issuecomment-1551415889), I somehow forgot to use `--muhome`, which is why it started working again. 

(If only I knew why I wanted to use `--muhome` ...)

**Comment by tmalsburg** [comment]
Glad to hear that you could figure it out.  Let me know if there is something that could be done to help avoid future problems.

**Comment by timmli** [comment]
Just FYI: the real problem was that I didn't tell helm-mu where to look for my mails when calling mu. This can be achieved with setting `helm-mu-command-arguments` in the following way, assuming that `mu4e-mu-home` contains the path to the mu folder:

`(setq helm-mu-command-arguments (concat "--muhome=" mu4e-mu-home))`

Now everything works.
