### ISSUE TITLE
README:  remove (require 'helm-config)?

### ISSUE THREAD

**Issue by rdiaz02** [emacs-helm/helm-mu#57]
I think `(require 'helm-config)` should no longer be used: it leads to a harmeless warning/error because `helm-config` was removed from helm a while back (e.g., https://github.com/emacs-helm/helm/issues/2578). 

In my own config I use `(helm-mode 1)` before I have the `use-package` block for `helm-mu` (which itself is inside the `use-package` block for mu4e). But even if it works, I am not sure if `(helm-mode 1)`  is the best/orthodox/minimal way of doing it.

I can make a pull request if it helps.

**Comment by thierryvolpiatto** [comment]
Ramon Diaz-Uriarte ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> I think (require 'helm-config) should no longer be used: it leads to a
> harmeless warning/error because helm-config was removed from helm a
> while back (e.g., emacs-helm/helm#2578).

Indeed, you should use instead `(require 'helm)`.
Where did you see (require 'helm-config) in documentation?
Normally I removed all such recommendations, but may be I missed one?

> In my own config I use (helm-mode 1) before I have the use-package
> block for helm-mu (which itself is inside the use-package block for
> mu4e). But even if it works, I am not sure if (helm-mode 1) is the
> best/orthodox/minimal way of doing it.

Of doing what?
As said above you can use:

    (require 'helm)
    (helm-mode 1)

But indeed helm-mode is itself loading helm, so (require 'helm) is
optional unless one is not using helm-mode.

> I can make a pull request if it helps.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.*Message ID: ***@***.***>

-- 
Thierry

**Comment by rdiaz02** [comment]
> Indeed, you should use instead `(require 'helm)`. Where did you see (require 'helm-config) in documentation? Normally I removed all such recommendations, but may be I missed one?

In the README file here: https://github.com/emacs-helm/helm-mu

right under "Install": https://github.com/emacs-helm/helm-mu#install


> Of doing what? 

Of loading the minimally required helm for  `helm-mu` work.

> As said above you can use: (require 'helm) (helm-mode 1) But indeed helm-mode is itself loading helm, so (require 'helm) is optional unless one is not using helm-mode.

Thanks! Understood.

In my specific case, I am using helm, so `(helm-mode 1)`  is the right thing to do, but I am not sure if someone might want to use `helm-mu`  without using `helm-mode`;  I guess maybe? And then, in such a case, they'd want to use `(require 'helm)`.

**Comment by thierryvolpiatto** [comment]
Ramon Diaz-Uriarte ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
>     Indeed, you should use instead (require 'helm). Where did you see (require 'helm-config) in documentation? Normally I removed all such recommendations, but may be I missed one?
>    
> In the README file here: https://github.com/emacs-helm/helm-mu
>
> right under "Install": https://github.com/emacs-helm/helm-mu#install

Thanks, fixed.

>     Of doing what?
>    
> Of loading the minimally required helm for helm-mu work.
>
>     As said above you can use: (require 'helm) (helm-mode 1) But indeed helm-mode is itself loading helm, so (require 'helm) is optional unless one is not using helm-mode.
>    
> Thanks! Understood.
>
> In my specific case, I am using helm, so (helm-mode 1) is the right
> thing to do,

You can use helm without helm-mode, using helm-mode allows one to
helmize all the completions coming from outside helm, but you don't have
to use helm-mode to use native helm commands e.g. helm-find-files,
helm-M-x etc...

> but I am not sure if someone might want to use helm-mu without using
> helm-mode; I guess maybe? And then, in such a case, they'd want to use
> (require 'helm).

Yes.


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
@tmalsburg , I updated the README.

**Comment by rdiaz02** [comment]
Thank you!!

**Comment by tmalsburg** [comment]
Thanks both. I'm going to close this issue.
