### ISSUE TITLE
Is there a way / workaround to use helm-mu-contacts to send to a group of emails?

### ISSUE THREAD

**Issue by jacopods** [emacs-helm/helm-mu#58]
For instance, could helm-mu-contacts parse ~/.mailrc as well?

**Comment by tmalsburg** [comment]
Fire up helm-mu-contacts and then use `M-SPC` to mark multiple entries. This is a standard helm feature.

**Comment by jacopods** [comment]
My apologies, I did not phrase my question properly. 

Of course what you suggest works, but I wonder if there is a way to "save" a group of contacts for future use. 

For instance I would like a create a group of contacts and call them "committee xyz". Then searching for "committee xyz" would bring up the emails of all components of the group.  Mailrc allows aliases to provide a similar feature.

Thanks for your time

**Comment by tmalsburg** [comment]
Oh, I see. No, that’s not supported. Helm-mu-contacts simply gives you access to all the contacts that the mu indexer found in your inbox. That’s all it does. Sorry

**Comment by jacopods** [comment]
OK, I understand.

Thanks a lot for your reply, and your work!

Best wishes,
  Jacopo
  

Titus von der Malsburg ***@***.***> writes:

> Oh, I see. No, that’s not supported. Helm-mu-contacts simply gives
> you access to all the contacts that the mu indexer found in your
> inbox. That’s all it does. Sorry
>
> -
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.*Message ID: 
> ***@***.***>

-- 
Jacopo De Simoi (he · him)
Professor · U Toronto
